<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="64" started-at="2015-08-10T13:27:30Z" finished-at="2015-08-10T13:27:30Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="64" started-at="2015-08-10T13:27:30Z" finished-at="2015-08-10T13:27:30Z">
      <class name="com.mi.testng.GoogleTests">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.mi.testng.GoogleTests@34340fab]" name="setUp" is-config="true" duration-ms="16" started-at="2015-08-10T08:27:30Z" finished-at="2015-08-10T08:27:30Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="a()[pri:0, instance:com.mi.testng.GoogleTests@34340fab]" name="a" duration-ms="8" started-at="2015-08-10T08:27:30Z" finished-at="2015-08-10T08:27:30Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- a -->
        <test-method status="FAIL" signature="verifyTitle()[pri:0, instance:com.mi.testng.GoogleTests@34340fab]" name="verifyTitle" duration-ms="6" started-at="2015-08-10T08:27:30Z" finished-at="2015-08-10T08:27:30Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<abc> but was:<Google>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<abc> but was:<Google>
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:101)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:108)
	at com.mi.testng.GoogleTests.verifyTitle(GoogleTests.java:15)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyTitle -->
      </class> <!-- com.mi.testng.GoogleTests -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
